### ISSUE TITLE
Catalog error

### ISSUE THREAD

**Issue by AlexSamad** [markt-de/puppet-ds_389#1]
Hi

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: 
Error while evaluating a Resource Statement, Evaluation Error: 
Resource type not found: Ssl_pkey (file: /etc/puppetlabs/code/environments/production/modules/ds_389/manifests/instance.pp, line: 283, column: 22) (file: /etc/puppetlabs/code/environments/production/site/role/manifests/ybcentos8.pp, line: 72) 
```

    # Create nss db.
    -> exec { "Create cert DB: ${server_id}":
      command     => "certutil -N -d ${instance_path} -f ${temp_pass_file}",
      path        => $ds_389::path,
      refreshonly => true,
      notify      => Ssl_pkey["Generate CA private key: ${server_id}"],
    }

    # Generate the private key for the CA.
    -> ssl_pkey { "Generate CA private key: ${server_id}":
      ensure => 'present',
      name   => $ca_key,
      size   => 4096,
    }

Think there is a case issue ?

**Comment by fraenki** [comment]
> Think there is a case issue ?

No, when specifying resource reference the resource type [should be capitalized](https://puppet.com/docs/puppet/6.19/lang_data_resource_reference.html). The unit tests also pass.

I think you haven't installed the required [camptocamp/puppet-openssl](https://github.com/camptocamp/puppet-openssl) module.
